name: Build and Test
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]

concurrency:
  group: "${% raw %}{{ github.workflow }} @ ${% raw %}{{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: [ cko-fort-default-runners-github-runners ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - id: codeartifact-token
        name: Retrieve CodeArtifact token
        uses: cko-fort/tl-git-actions/codeartifact-token@v1

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and run docker containers
        run: |
          ./docker-pipeline.sh
        env:
          CODEARTIFACT_AUTH_TOKEN: ${{ steps.codeartifact-token.outputs.codeartifact_auth_token }}

      - name: Localstack log
        run: |
          docker logs localstack
