spring:
  kafka:
    producer:
      properties:
        bootstrap.servers: '${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}'
        schema.registry.url: 'http://${SCHEMA_REGISTRY_ENDPOINT:localhost}:8085'
localstack:
  endpoint: 'http://${LOCALSTACK_AWS_ENDPOINT:localhost}:4566'