package com.checkout.settlement.{{ cookiecutter.scheme_slug }}.tc33.model;

import lombok.Builder;

@Builder(toBuilder=true)
public record CAS(
    String fileName,
    int lineNumber,
    String lineContents,
    String recordType,
    String transactionCode,
    String transactionCodeQualifier,
    String transactionComponentSequenceNumber,
    String destinationBin,
    String sourceBin,
    String casAdviceRecordId,
    String originatorRecipientIndicator,
    String transactionCodeOfFinancialTransaction,
    String tcqOfFinancialTransaction,
    String centralProcessingDate,
    String transactionIdentifier,
    String accountNumber,
    String accountNumberExtension,
    String acquirerReferenceNumber,
    String cardAcceptorId,
    String terminalId,
    String sourceAmount,
    String sourceCurrencyCode,
    String settlementFlag,
    String settlementServiceId,
    String settlementCurrency,
    String leafLevelSreId,
    String fundsTransferSreId,
    String settlementAmountInterchange,
    String settlementAmountSign,
    String usageCode,
    String reclassificationIndicator,
    String requestedPaymentService,
    String reserved,

    String interchangeFeeAmount,
    String interchangeFeeSign,
    String merchantVerificationValue,
    String feeProgramIndicator,
    String feeDescriptor,
    String conversionDate,
    String settlementDate,
    String base2UniqueFileId,
    String persistentFxAppliedIndicator,
    String rateTableId,
    String additionalTokenResponseInformation,
    String agreementId,
    String enablerVerificationValue,
    String visaMerchantIdentifier,
    String reserved1
) implements Tc33Record {
}
