package com.checkout.settlement.{{ cookiecutter.scheme_slug }}.confirmation.model;

public record Charge(
    String fileName,
    int lineNumber,
    String lineContents,
    String recordType,
    String sequenceNumber,
    String cardNumber,
    String chargeDate,
    String chargeType,
    String typeOfCharge,
    String referenceNumber,
    String authorizationNumber,
    String programTransactionRate,
    String interchangePTFinUSD,
    String grossChargeAmount,
    String netChargeAmount,
    String alternateCurrencyGrossAmount,
    String alternateCurrencyNetAmount,
    String interchangeCommissionInTransactionCurrency,
    String interchangeCommissionInAlternateCurrency,
    String grossSettlementAmount,
    String netSettlementAmount,
    String interchangeCommissionSettlementAmount,
    String grossSettlementAmountInUSD,
    String netSettlementAmountInUSD,
    String interchangeCommissionInUSD,
    String interchangePTFInSettlementCurrency,
    String pricingRuleName,
    String pricingRuleCode,
    String pricingRuleSerialNumber,
    String settlementDate,
    String eci,
    String cavv,
    String networkReferenceId,
    String ATMInterchangeFeeInUSD,
    String ATMSecurityFeeInUSD,
    String ATMNetworkInternationalProcessingFeeInUSD,
    String ATMInterchangeFeeInSettlementCurrency,
    String ATMSecurityFeeInSettlementCurrency,
    String ATMNetworkInternationalProcessingFeeInSettlementCurrency,
    String surchargeFee,
    String acquirerGeoCode,
    String cardProductType,
    String mccCode,
    String intesCode,
    String merchantId,
    String cardholderPresent,
    String cardPresent,
    String captureMethod,
    String merchantGeoCode,
    String issuerGeoCode,
    String merchantPAN,
    String specialConditionsIndicator,
    String filler) implements ConfirmationRecord {
}
